development:
  adapter: postgresql
  encoding: unicode
  database: netflixed
  pool: 2
  username: sharnajhossain
  password: Lazzer12
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['netflixed'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>